apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170736869
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170736869
    app.kubernetes.io/part-of: test-app-170736869
  name: go-170736869iok5
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-170736869
    weight: null
status: {}
